# Generated by Django 4.1.1 on 2022-09-08 20:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('marca', models.CharField(choices=[('Motorola', 'Motorola'), ('Samsung', 'Samsung'), ('Lg', 'Lg'), ('Xiaomi', 'Xiaomi'), ('Sony', 'Sony'), ('Huawey', 'Huawey'), ('Chino', 'Chino'), ('Otro', 'Otro')], max_length=40)),
                ('modelo', models.CharField(blank=True, max_length=40)),
                ('imei', models.CharField(blank=True, max_length=40)),
                ('falla', models.CharField(max_length=40)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fallas')),
                ('comentarios', ckeditor.fields.RichTextField(null=True)),
                ('presupuesto', models.IntegerField(blank=True, null=True)),
                ('precio', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Reparado', 'Reparado'), ('Irreparable', 'Irreparable'), ('Entregado', 'Entregado'), ('Entregado Irreparable', 'Entregado Irreparable')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TareasPendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='IngresoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('marca', models.CharField(choices=[('Motorola', 'Motorola'), ('Samsung', 'Samsung'), ('Lg', 'Lg'), ('Xiaomi', 'Xiaomi'), ('Sony', 'Sony'), ('Huawey', 'Huawey'), ('Chino', 'Chino'), ('Otro', 'Otro')], max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('imei', models.CharField(max_length=40)),
                ('accesorios', models.CharField(max_length=40)),
                ('falla', models.CharField(max_length=40)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fallas')),
                ('comentarios', ckeditor.fields.RichTextField()),
                ('precio', models.IntegerField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mi_web.cliente')),
            ],
        ),
    ]
